### ISSUE TITLE
Bug al actualizar estado cama

### ISSUE THREAD

**Issue by nelsonllez** [jacalistre/SGCA#1]
La aplicación arroja una excepción cuando se realizan las acciones:
-  reubicar dentro del centro
- retirar ubicación
La llamada a la función ActualizarEstadoCama en src/Repository/CamaRepository.php arroja el error: Commands out of sync; you can't run this command now.

Se propone realizar una refactorización de la función con el siguiente código:

public function ActualizarEstadoCama($idcama,$estado)
    {
        return $this->createQueryBuilder('c')
            ->update()
            ->set('c.estado', ':estado')
            ->where('c.id = :cama')
            ->setParameter('estado', $estado)
            ->setParameter('cama', $idcama)
            ->getQuery()
            ->execute();
    }

las pruebas resultaron satisfactorias.

Saludos cordiales,

Nelson (Guantánamo)

**Comment by jacalistre** [comment]
Bien!!!
